/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_DIGITAL_EN 0x0100u /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u        /*!<@brief Selects pin function 1 */
#define IOCON_PIO_INV_DI 0x00u       /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u   /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_FAST 0x40u    /*!<@brief Fast mode, slew rate control is disabled */

/*! @name PIO0_29 (number 92), DEBUG_UART_RX
  @{ */
#define BOARD_INIT_DEBUG_DEBUG_UART_RX_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_DEBUG_DEBUG_UART_RX_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INIT_DEBUG_DEBUG_UART_RX_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PIO0_30 (number 94), DEBUG_UART_TX
  @{ */
#define BOARD_INIT_DEBUG_DEBUG_UART_TX_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_DEBUG_DEBUG_UART_TX_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INIT_DEBUG_DEBUG_UART_TX_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_INIT_DEBUG(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_20_FUNC_ALT5 0x05u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_20_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_21_FUNC_ALT5 0x05u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_21_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_6_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_6_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_6_SLEW_FAST 0x01u

/*! @name PIO1_21 (number 30), MPU6050_SDA
  @{ */
#define BOARD_INIT_MPU6050_MPU6050_SDA_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_MPU6050_MPU6050_SDA_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INIT_MPU6050_MPU6050_SDA_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PIO1_20 (number 4), MPU6050_SCL
  @{ */
#define BOARD_INIT_MPU6050_MPU6050_SCL_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_MPU6050_MPU6050_SCL_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INIT_MPU6050_MPU6050_SCL_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PIO1_6 (number 5), MPU6050_INT
  @{ */
#define BOARD_INIT_MPU6050_MPU6050_INT_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_MPU6050_MPU6050_INT_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INIT_MPU6050_MPU6050_INT_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_INIT_MPU6050(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_15_MODE_PULL_UP 0x02u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_15_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_5_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_5_MODE_PULL_UP 0x02u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_5_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_8_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_8_MODE_PULL_UP 0x02u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_8_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_9_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_9_MODE_PULL_UP 0x02u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_9_SLEW_FAST 0x01u

/*! @name PIO1_5 (number 31), ENCA_CLK
  @{ */
#define BOARD_INIT_ENC_ENCA_CLK_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_ENC_ENCA_CLK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INIT_ENC_ENCA_CLK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO1_9 (number 10), ENCB_CLK
  @{ */
#define BOARD_INIT_ENC_ENCB_CLK_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_ENC_ENCB_CLK_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INIT_ENC_ENCB_CLK_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_15 (number 22), ENCA_ST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_ENC_ENCA_ST_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INIT_ENC_ENCA_ST_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */
#define BOARD_INIT_ENC_ENCA_ST_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_ENC_ENCA_ST_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INIT_ENC_ENCA_ST_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO1_8 (number 24), ENCB_ST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_ENC_ENCR_ST_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INIT_ENC_ENCR_ST_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */
#define BOARD_INIT_ENC_ENCR_ST_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_ENC_ENCR_ST_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INIT_ENC_ENCR_ST_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_INIT_ENC(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO0_26_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_1_FUNC_ALT5 0x05u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO1_1_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_26_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_26_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO1_26_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_27_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_27_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_27_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO1_27_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_2_FUNC_ALT6 0x06u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO1_2_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_3_FUNC_ALT6 0x06u

/*! @name PIO1_1 (number 59), LCD_SSEL1
  @{ */
#define BOARD_INIT_LCD_LCD_SSEL1_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_LCD_LCD_SSEL1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INIT_LCD_LCD_SSEL1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO1_2 (number 61), LCD_SCK
  @{ */
#define BOARD_INIT_LCD_LCD_SCK_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_LCD_LCD_SCK_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INIT_LCD_LCD_SCK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_26 (number 60), LCD_MOSI
  @{ */
#define BOARD_INIT_LCD_LCD_MOSI_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_LCD_LCD_MOSI_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INIT_LCD_LCD_MOSI_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO1_27 (number 85), LCD_DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_LCD_LCD_DC_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INIT_LCD_LCD_DC_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */
#define BOARD_INIT_LCD_LCD_DC_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_LCD_LCD_DC_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INIT_LCD_LCD_DC_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO1_26 (number 68), LCD_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_LCD_LCD_RST_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INIT_LCD_LCD_RST_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define BOARD_INIT_LCD_LCD_RST_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_LCD_LCD_RST_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INIT_LCD_LCD_RST_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_INIT_LCD(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_31_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_31_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_31_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_31_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_7_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_7_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_7_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_0_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_0_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_0_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_10_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_10_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_10_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO1_4_FUNC_ALT3 0x03u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_4_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO1_7_FUNC_ALT3 0x03u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_7_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_7_SLEW_FAST 0x01u

/*! @name PIO1_7 (number 9), PWM_BR
  @{ */
#define PBOARD_INIT_ENGINE_PWM_BR_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PBOARD_INIT_ENGINE_PWM_BR_PIN 7U                   /*!<@brief PORT pin number */
#define PBOARD_INIT_ENGINE_PWM_BR_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_7 (number 6), BIN_R
  @{ */

/* Symbols to be used with GPIO driver */
#define PBOARD_INIT_ENGINE_BIN_R_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PBOARD_INIT_ENGINE_BIN_R_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define PBOARD_INIT_ENGINE_BIN_R_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define PBOARD_INIT_ENGINE_BIN_R_PIN 7U                   /*!<@brief PORT pin number */
#define PBOARD_INIT_ENGINE_BIN_R_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO1_0 (number 11), BIN_L
  @{ */

/* Symbols to be used with GPIO driver */
#define PBOARD_INIT_ENGINE_BIN_L_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PBOARD_INIT_ENGINE_BIN_L_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define PBOARD_INIT_ENGINE_BIN_L_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PBOARD_INIT_ENGINE_BIN_L_PIN 0U                   /*!<@brief PORT pin number */
#define PBOARD_INIT_ENGINE_BIN_L_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_31 (number 23), AIN_L
  @{ */

/* Symbols to be used with GPIO driver */
#define PBOARD_INIT_ENGINE_AIN_L_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PBOARD_INIT_ENGINE_AIN_L_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */
#define PBOARD_INIT_ENGINE_AIN_L_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PBOARD_INIT_ENGINE_AIN_L_PIN 31U                   /*!<@brief PORT pin number */
#define PBOARD_INIT_ENGINE_AIN_L_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_10 (number 40), Ain_R
  @{ */

/* Symbols to be used with GPIO driver */
#define PBOARD_INIT_ENGINE_AIN_R_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PBOARD_INIT_ENGINE_AIN_R_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */
#define PBOARD_INIT_ENGINE_AIN_R_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PBOARD_INIT_ENGINE_AIN_R_PIN 10U                   /*!<@brief PORT pin number */
#define PBOARD_INIT_ENGINE_AIN_R_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PBOARD_INIT_ENGINE(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_23_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_23_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_23_MODE_PULL_UP 0x02u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_23_SLEW_FAST 0x01u

/*! @name PIO0_23 (number 20), BUTTON
  @{ */
#define BOARD_INIT_BUTTON_INT_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_BUTTON_INT_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INIT_BUTTON_INT_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_23 (number 20), BUTTON
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_BUTTON_GPIO_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INIT_BUTTON_GPIO_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */
#define BOARD_INIT_BUTTON_GPIO_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_BUTTON_GPIO_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INIT_BUTTON_GPIO_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_INIT_BUTTON(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_16_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_16_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_16_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_16_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_16_SLEW_FAST 0x01u

/*! @name PIO0_16 (number 14), ADC_BATTERY
  @{ */
#define BOARD_INIT_ADC_ADC_BATTERY_GPIO GPIO                 /*!<@brief GPIO device name: GPIO */
#define BOARD_INIT_ADC_ADC_BATTERY_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INIT_ADC_ADC_BATTERY_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INIT_ADC_ADC_BATTERY_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_INIT_ADC(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
